### ISSUE TITLE
Blue orb reduced max health - dmc3

### ISSUE THREAD

**Issue by PlugSocket23** [serpentiem/ddmk#235] opened 2021-09-09 21:01 UTC
In dmc3, In mission 5, just before the boss fight against Agni & Rudra I bought a blue orb at the statue and it **reduced** my max health instead of increasing it. Buying more blue orbs **did** increase max health.

I'm using DDMK 2.7 Eva Lucia Mary Nightly 5 September 2021. I don't have any other mods so I'm assuming this is the cause.

**Comment by serpentiem** [comment] 2021-09-10 09:15
Super interesting, because there is no reduction logic. Can you reproduce it or do you still have the save from that time?

**Comment by PlugSocket23** [comment] 2021-09-11 21:47
https://user-images.githubusercontent.com/75939496/132962348-0494046c-541c-475f-8ae9-50dcc8c707ff.mp4

Seems to happen at any statue, the one I mentioned before is just the first time it happened.

**Comment by serpentiem** [comment] 2021-09-12 19:58
Found the bug: I'm an idiot. I used the current hit & magic points instead of the max ones. Will be fixed in the next nightly. Thanks for reporting!

**Closed by serpentiem** 2021-09-12 19:58 UTC

**Comment by PlugSocket23** [comment] 2021-09-12 20:25
No worries, and btw you're not an idiot, that's an easy mistake to make (:

Also I find it a bit funny that I can make the health bar look like this:
![Devil May Cry HD Collection 12_09_2021 21_23_11](https://user-images.githubusercontent.com/75939496/133001762-bd5a2067-efd6-4526-a235-c254c0f55e3a.png)
