### ISSUE TITLE
DMC1 game is unplayable from mission 3 it is still unable in beta 2

### ISSUE THREAD

**Issue by fileo919** [serpentiem/ddmk#93] opened 2020-01-10 16:15 UTC
From mission 3, the game starts with very strange view and I can attack but the camera doesn't change and nothing works except attacks. I think it is problem on every missions except first two missions.

**Comment by serpentiem** [comment] 2020-02-04 09:32
That's a known bug, I'll look into it.

A temporary solution:

* Enable Arcade mode.
* Check `Ignore` right next to `Room`.
* Disable Arcade mode.

**Comment by 69NEPHILIM69** [comment] 2020-04-19 11:11
I roughly understood what exactly the problem is, the dante will spawn in the wrong place at the beginning of the mission, maybe this will help fix the bug

> That's a known bug, I'll look into it.
> 
> A temporary solution:
> 
> * Enable Arcade mode.
> * Check `Ignore` right next to `Room`.
> * Disable Arcade mode.

**Comment by serpentiem** [comment] 2021-02-17 14:23
Merged with #184.

**Closed by serpentiem** 2021-02-17 14:23 UTC
Labels: bug, dmc1, research
