### ISSUE TITLE
[Bug] A problem when switching between Windowed and Full Screen Modes using the ALT+Enter key on DMC3SE

### ISSUE THREAD

**Issue by GitHubro5** [serpentiem/ddmk#230] opened 2021-08-28 18:00 UTC
Hello.

I am currently using DDMK 2.7 Mary Nightly 30 June 2021 on DMC3SE.

After I install DDMK (even with all defaults value), when I switch between window mode and full screen mode with ALT+Enter keys, I get a problem that doesn't work at once.
For example, when I press the Alt+Enter key in the current window mode, the screen flashes once and then goes back to window mode.

I have to press it several times to switch.

The other problem is...
There is a problem with window beeps that sound Ding~! when switching between window modes.
Mainly, when trying to switch from window mode to full screen mode, there is a problem that does not switch after beep.
However, when switching from full screen mode to window mode, the transition works even when the beep sounds.

But I don't know why the beep is ringing.

**Comment by serpentiem** [comment] 2021-09-07 12:34
I can't reproduce these problems.

**Comment by SteveCraft1** [comment] 2021-09-07 15:36
> Hello.
> 
> I am currently using DDMK 2.7 Mary Nightly 30 June 2021 on DMC3SE.
> 
> After I install DDMK (even with all defaults value), when I switch between window mode and full screen mode with ALT+Enter keys, I get a problem that doesn't work at once.
> For example, when I press the Alt+Enter key in the current window mode, the screen flashes once and then goes back to window mode.
> 
> I have to press it several times to switch.

**Comment by serpentiem** [comment] 2022-01-10 13:58
Closing.

**Closed by serpentiem** 2022-01-10 13:58 UTC
