### ISSUE TITLE
Artemis multi target not working

### ISSUE THREAD

**Issue by bill5499** [serpentiem/ddmk#216] opened 2021-07-07 10:13 UTC
Okay I just noticed that the Artemis normal charge shot which allows it to lock on and fire on multiple targets is not working when I enabled Actor. Is this a bug or intentional?

**Comment by Proutbedaine** [comment] 2021-07-07 10:16
If I remember correctly in the list of features he swapped the normal shot (that you can charge and lock on on multiple targets) with the multi-shot that you normally need Gunslinger Style active to be able to use it with the circle/B button.

Can't rmember if it was optional or not. I hope it is.

**Comment by bill5499** [comment] 2021-07-07 10:19
> 
> 
> If I remember correctly in the list of features he swapped the normal shot (that you can charge and lock on on multiple targets) with the multi-shot that you normally need Gunslinger Style active to be able to use it with the circle/B button.
> 
> Can't rmember if it was optional or not. I hope it is.

... Why is that a thing? If you're gonna enabled style switcher you're gonna be able to use the Gunslinger multi lock anyway. Ugh it's so fucking confusing.

**Comment by SteveCraft1** [comment] 2021-07-07 10:27
> > 
> > 
> > If I remember correctly in the list of features he swapped the normal shot (that you can charge and lock on on multiple targets) with the multi-shot that you normally need Gunslinger Style active to be able to use it with the circle/B button.
> > 
> > Can't rmember if it was optional or not. I hope it is.
> 
> ... Why is that a thing? If you're gonna enabled style switcher you're gonna be able to use the Gunslinger multi lock anyway. Ugh it's so fucking confusing. 

It's probably to make It using multi shoot easier for some people,on some combo vídeos multi shoot is alot used to keep the enemy on the air

**Comment by SteveCraft1** [comment] 2021-07-07 10:30
Also If the problem is "It can shoot but It never shoot directly to the enemy" then DDMK probably messed up or something(i'm not the creator so i can't confirm It) this,because on Artemis,you need to hold Lock on and press shoot or hold It to make Dante really use Artemis and shoot directly to the enemy,this same issue also happen on multi shoot,If you don't hold Lock on,you can never charge it or shoot to the enemy(this happen both on gunslinger multi shoot and normal shoot)

**Comment by bill5499** [comment] 2021-07-07 10:31
> 
> 
> > > If I remember correctly in the list of features he swapped the normal shot (that you can charge and lock on on multiple targets) with the multi-shot that you normally need Gunslinger Style active to be able to use it with the circle/B button.
> > > Can't rmember if it was optional or not. I hope it is.
> > 
> > 
> > ... Why is that a thing? If you're gonna enabled style switcher you're gonna be able to use the Gunslinger multi lock anyway. Ugh it's so fucking confusing.
> 
> It's probably to make It using multi shoot easier for some people,on some combo vídeos multi shoot is alot used to keep the enemy on the air

Still doesn't explain why they needed it map to the normal shot button instead of using the same set up as Gunslinger mode. It's still the same damm thing , just different buttons. If anything this just makes it more confusing

**Comment by bill5499** [comment] 2021-07-07 10:33
> Also If the problem is "It can shoot but It never shoot directly to the enemy" then DDMK probably messed up or something(i'm not the creator so i can't confirm It) this,because on Artemis,you need to hold Lock on and press shoot or hold It to make Dante really use Artemis and shoot directly to the enemy,this same issue also happen on multi shoot,If you don't hold Lock on,you can never charge it or shoot to the enemy(this happen both on gunslinger multi shoot and normal shoot)

The problem is when I try charging the normal shot, instead of locking on multiple targets and then release a bunch of orbs that flies in multiple directions to hit the targets, it just fire one normal beam like it was never even charged in the first place

**Comment by SteveCraft1** [comment] 2021-07-07 10:37
Also it's a optional thing to make this swap,i'm still using the default(normal shoot by button and multi shoot by gunslinger) because i'm still getting used to remove busy Flag,but while It don't make sense,it's to make It more practical to use,not everyone can hold Lock on,hold gunslinger button while moving to use multi shoot,like me which my keyboard don't allow me to do It forcing me to keep idle while charging It.

**Comment by bill5499** [comment] 2021-07-07 10:39
> 
> 
> Also it's a optional thing to make this swap,i'm still using the default(normal shoot by button and multi shoot by gunslinger) because i'm still getting used to remove busy Flag,but while It don't make sense,it's to make It more practical to use,not everyone can hold Lock on,hold gunslinger button while moving to use multi shoot,like me which my keyboard don't allow me to do It forcing me to keep idle while charging It.

I don't think that's the issue though. I never even touch anything besides the enabling actor button. So unless the swap was on by default, that's not it.

**Comment by SteveCraft1** [comment] 2021-07-07 13:43
i did some testings and Artemis bug alot when Actor is enabled,the problems i found was
If you don't hold lock on while charging(normal shoot),you can't shoot on more than one enemy(that move where a bunch of energy balls split to hit each enemy),the same also applies to multi shoot from gunslinger
Stop holding lock on before shooting will reset charge and you will only shoot one energy ball
also i verified and by default DDMK don't swap normal shoot and multi shoot,you can only activated it in Dante module and anything there can be activated to use without actor module.

**Comment by bill5499** [comment] 2021-07-07 13:51
> 
> 
> i did some testings and Artemis bug alot when Actor is enabled,the problems i found was
> If you don't hold lock on while charging(normal shoot),you can't shoot on more than one enemy(that move where a bunch of energy balls split to hit each enemy),the same also applies to multi shoot from gunslinger
> Stop holding lock on before shooting will reset charge and you will only shoot one energy ball
> also i verified and by default DDMK don't swap normal shoot and multi shoot,you can only activated it in Dante module and anything there can be activated to use without actor module.

Kinda weird how that works. That extra step of pressing the lock on button is just unnecessary. As if people don't got enough buttons to remember about in this game.

**Comment by serpentiem** [comment] 2021-09-08 16:56
Thanks for reporting. Added to #234.

**Closed by serpentiem** 2021-09-08 16:56 UTC
